source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZKeyboardAdjust_Example', :exclusive => true do
  pod 'DZKeyboardAdjust', :path => '../'
end

target 'DZKeyboardAdjust_Tests', :exclusive => true do
  pod 'DZKeyboardAdjust', :path => '../'

  pod 'FBSnapshotTestCase'
end
